# Generated by Django 4.2.8 on 2026-01-07 15:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studios', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('type', models.CharField(choices=[('drop_in', 'Drop-in'), ('package', 'Paquete'), ('membership', 'Membresía')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(default='MXN', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('meta', models.JSONField(default=dict)),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='studios.studio')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['studio'], name='products_studio__5480c8_idx'), models.Index(fields=['type'], name='products_type_0590f2_idx')],
                'unique_together': {('studio', 'type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('full_name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to='studios.studio')),
            ],
            options={
                'db_table': 'instructors',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['studio'], name='instructors_studio__07e3a2_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClassType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_types', to='studios.studio')),
            ],
            options={
                'db_table': 'class_types',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['studio'], name='class_types_studio__b935d5_idx')],
                'unique_together': {('studio', 'name')},
            },
        ),
    ]
