# Generated by Django 4.2.8 on 2026-01-07 15:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studios', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('event', models.CharField(max_length=100)),
                ('target_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to='studios.studio')),
            ],
            options={
                'db_table': 'webhook_endpoints',
                'indexes': [models.Index(fields=['studio', 'event'], name='webhook_end_studio__f2c8da_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('code', models.CharField(max_length=100)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS')], max_length=30)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_templates', to='studios.studio')),
            ],
            options={
                'db_table': 'notification_templates',
                'unique_together': {('studio', 'code', 'channel')},
            },
        ),
    ]
