# Generated by Django 4.2.8 on 2026-01-07 15:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studios', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('event_type', models.CharField(max_length=50)),
                ('utm', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('studio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='studios.studio')),
            ],
            options={
                'db_table': 'tracking_events',
            },
        ),
    ]
