# Generated by Django 4.2.8 on 2026-01-07 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='trackingevent',
            index=models.Index(fields=['studio', 'created_at'], name='tracking_ev_studio__4bd7c7_idx'),
        ),
    ]
