# Generated by Django 4.2.8 on 2026-01-07 15:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studios', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.CharField(choices=[('booked', 'Reservado'), ('waitlist', 'Espera'), ('cancelled', 'Cancelado'), ('no_show', 'No show'), ('attended', 'Asistió')], default='booked', max_length=20)),
                ('booked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('checked_in_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('method', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'checkins',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('starts_at', models.DateTimeField()),
                ('capacity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('scheduled', 'Programada'), ('cancelled', 'Cancelada'), ('done', 'Realizada')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sessions',
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('position', models.PositiveIntegerField()),
                ('offered_until', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='scheduling.session')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='studios.studio')),
            ],
            options={
                'db_table': 'waitlist_entries',
                'ordering': ['position', 'created_at'],
            },
        ),
    ]
