# Generated by Django 4.2.8 on 2026-01-07 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
        ('studios', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlistentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='session',
            name='class_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='catalog.classtype'),
        ),
        migrations.AddField(
            model_name='session',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='catalog.instructor'),
        ),
        migrations.AddField(
            model_name='session',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='studios.location'),
        ),
        migrations.AddField(
            model_name='session',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='studios.studio'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkin', to='scheduling.booking'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='studios.studio'),
        ),
        migrations.AddField(
            model_name='booking',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='scheduling.session'),
        ),
        migrations.AddField(
            model_name='booking',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='studios.studio'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='waitlistentry',
            index=models.Index(fields=['session', 'position'], name='waitlist_en_session_a45d0c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='waitlistentry',
            unique_together={('session', 'user')},
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['studio', 'starts_at'], name='sessions_studio__4dcc8f_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['status'], name='sessions_status_2c94db_idx'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['studio'], name='checkins_studio__3658b5_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['session'], name='bookings_session_28a56e_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user'], name='bookings_user_id_fdc49e_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='bookings_status_51373b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('session', 'user')},
        ),
    ]
