# Generated by Django 4.2.8 on 2026-01-07 15:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('brand_json', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('tz', models.CharField(default='America/Merida', max_length=64)),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='studios.studio')),
            ],
            options={
                'indexes': [models.Index(fields=['studio'], name='studios_loc_studio__fa1239_idx')],
            },
        ),
        migrations.CreateModel(
            name='LinkButton',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('label', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('kind', models.CharField(help_text='reservar|comprar|whatsapp|instagram|ubicacion|sitio|custom', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(default=1)),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_buttons', to='studios.studio')),
            ],
            options={
                'ordering': ['position'],
                'indexes': [models.Index(fields=['studio', 'position'], name='studios_lin_studio__d14b09_idx')],
            },
        ),
    ]
